services:

  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      MYSQL_DATABASE: SchoolDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    
    volumes:
    - ./mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: school-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/SchoolDB
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/SchoolDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"